-- Master Seed Data for Legend Games
-- Contains all 72 PlayStation 4 / PC / Xbox games
BEGIN TRANSACTION;

INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('a-way-out', 'A Way Out', 'Co-op / Action Adventure', 8.8, 2018, 'Best Co-op', 18, 25, 15000, 4500, 2000, '../shared/assets/covers/a-way-out.jpg', 'A cinematic split-screen co-op adventure about two prisoners escaping together.');
INSERT INTO game_platforms (game_id, platform) VALUES ('a-way-out', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('a-way-out', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('a-way-out', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('bloodborne', 'Bloodborne (PlayStation Hits)', 'Action RPG / Souls-like', 9.7, 2015, 'PlayStation Hit', 30, 0, 16000, 5000, 2000, '../shared/assets/covers/bloodborne.jpg', 'Hunt your nightmares in the gothic city of Yharnam. FromSoftware classic.');
INSERT INTO game_platforms (game_id, platform) VALUES ('bloodborne', 'ps4');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('cod-mw2', 'Call of Duty: Modern Warfare II', 'FPS / Action', 9.2, 2022, 'Blockbuster', 75, 85, 28000, 7000, 2500, '../shared/assets/covers/cod-mw2.jpg', 'Task Force 141 returns with intense tactical campaigns and Warzone firefights.');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-mw2', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-mw2', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-mw2', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-mw2', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('pes-2021', 'eFootball PES 2021 Season Update', 'Sports / Football', 8.9, 2020, 'Football Classic', 40, 42, 14000, 4000, 1500, '../shared/assets/covers/pes-2021.jpg', 'Master League, iconic football gameplay, and realistic stadium atmospheres.');
INSERT INTO game_platforms (game_id, platform) VALUES ('pes-2021', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('pes-2021', 'pc');
INSERT INTO game_platforms (game_id, platform) VALUES ('pes-2021', 'ps3');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('cod-cold-war', 'Call of Duty: Black Ops Cold War', 'FPS / Action', 9, 2020, 'Zombies & Campaign', 95, 110, 22000, 6000, 2500, '../shared/assets/covers/cod-cold-war.jpg', 'Gripping Cold War conspiracies, intense multiplayer, and classic Round-based Zombies.');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-cold-war', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-cold-war', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-cold-war', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-cold-war', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('cod-vanguard', 'Call of Duty: Vanguard', 'FPS / WWII Action', 8.5, 2021, 'WWII Shooter', 60, 70, 20000, 5500, 2000, '../shared/assets/covers/cod-vanguard.jpg', 'Experience pivotal WWII battles across the Eastern, Western, Pacific, and North African fronts.');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-vanguard', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-vanguard', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-vanguard', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-vanguard', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('ac-mirage', '', 'Action / Stealth', 8.9, 2023, 'Back to Roots', 38, 40, 25000, 6500, 2500, '../shared/assets/covers/ac-mirage.jpg', 'A homage to the original stealth roots in 9th-century Golden Age Baghdad.');
INSERT INTO game_platforms (game_id, platform) VALUES ('ac-mirage', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('ac-mirage', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('ac-mirage', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('ac-mirage', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('cod-bo3', 'Call of Duty: Black Ops III', 'FPS / Sci-Fi Action', 9.1, 2015, 'Zombies Chronicles', 55, 60, 15000, 4500, 2000, '../shared/assets/covers/cod-bo3.jpg', 'Advanced cybernetic warfare and the fan-favorite Zombies Chronicles collection.');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-bo3', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-bo3', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('cod-bo3', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('captain-tsubasa', 'Captain Tsubasa: Rise of New Champions', 'Anime / Sports', 8.7, 2020, 'Anime Soccer', 30, 32, 18000, 5000, 2000, '../shared/assets/covers/captain-tsubasa.jpg', 'Over-the-top arcade soccer action featuring iconic special shots and storylines.');
INSERT INTO game_platforms (game_id, platform) VALUES ('captain-tsubasa', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('captain-tsubasa', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('ctr-nitro-fueled', 'Crash Team Racing Nitro-Fueled', 'Arcade Racing / Family', 9.1, 2019, 'Family Favorite', 22, 0, 17000, 4500, 2000, '../shared/assets/covers/ctr-nitro-fueled.jpg', 'The authentic CTR experience plus tons of remastered tracks, karts, and characters.');
INSERT INTO game_platforms (game_id, platform) VALUES ('ctr-nitro-fueled', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('ctr-nitro-fueled', 'xbox');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('far-cry-6', 'Far Cry 6', 'Open World / FPS', 8.8, 2021, 'Open World', 60, 65, 20000, 5500, 2000, '../shared/assets/covers/far-cry-6.jpg', 'Join a modern guerrilla revolution to liberate the tropical paradise of Yara.');
INSERT INTO game_platforms (game_id, platform) VALUES ('far-cry-6', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('far-cry-6', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('far-cry-6', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('far-cry-6', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('gta-v', 'Grand Theft Auto V', 'Action / Open World', 9.9, 2022, 'All-Time Classic', 95, 110, 18000, 5000, 2000, '../shared/assets/covers/gta-v.jpg', 'Los Santos and Blaine County in ultra high definition. The ultimate heist sandbox.');
INSERT INTO game_platforms (game_id, platform) VALUES ('gta-v', 'ps3');
INSERT INTO game_platforms (game_id, platform) VALUES ('gta-v', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('gta-v', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('gta-v', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('gta-v', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('days-gone', 'Days Gone', 'Survival / Open World', 9, 2019, 'Freaker Hordes', 68, 70, 18000, 5000, 2000, '../shared/assets/covers/days-gone.jpg', 'Ride and fight across a brutal Pacific Northwest wilderness crawling with infected hordes.');
INSERT INTO game_platforms (game_id, platform) VALUES ('days-gone', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('days-gone', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('ea-sports-fc-26', 'EA SPORTS FC 26', 'Sports / Football', 9.4, 2025, 'Trending #1', 48, 55, 38000, 8000, 3000, '../shared/assets/covers/ea-sports-fc-26.jpg', 'HyperMotionV realism, updated clubs, Ultimate Team, and Career mode.');
INSERT INTO game_platforms (game_id, platform) VALUES ('ea-sports-fc-26', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('ea-sports-fc-26', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('ea-sports-fc-26', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('ea-sports-fc-26', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('horizon-forbidden-west', 'Horizon Forbidden West', 'Open World / Action RPG', 9.6, 2022, 'Stunning Visuals', 98, 120, 26000, 6500, 2500, '../shared/assets/covers/horizon-forbidden-west.jpg', 'Explore distant lands, fight bigger awe-inspiring machines, and encounter new tribes.');
INSERT INTO game_platforms (game_id, platform) VALUES ('horizon-forbidden-west', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('horizon-forbidden-west', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('horizon-forbidden-west', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('dirt-5', 'DIRT 5', 'Racing / Off-Road', 8.6, 2020, 'Off-Road Thrills', 42, 45, 16000, 4500, 2000, '../shared/assets/covers/dirt-5.jpg', 'Extreme off-road arcade racing across stunning global routes from NYC to Brazil.');
INSERT INTO game_platforms (game_id, platform) VALUES ('dirt-5', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('dirt-5', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('dirt-5', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('dirt-5', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('ghost-of-tsushima', 'Ghost of Tsushima', 'Action / Samurai Adventure', 9.8, 2020, 'PlayStation Masterpiece', 60, 75, 24000, 6000, 2500, '../shared/assets/covers/ghost-of-tsushima.jpg', 'Unconventional samurai warfare to protect feudal Japan from the Mongol invasion.');
INSERT INTO game_platforms (game_id, platform) VALUES ('ghost-of-tsushima', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('ghost-of-tsushima', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('ghost-of-tsushima', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('hot-wheels-unleashed', 'Hot Wheels Unleashed', 'Arcade Racing / Party', 8.7, 2021, 'High-Octane Fun', 20, 22, 15000, 4000, 2000, '../shared/assets/covers/hot-wheels-unleashed.jpg', 'Collect the best Hot Wheels vehicles, build extraordinary tracks, and race in split-screen.');
INSERT INTO game_platforms (game_id, platform) VALUES ('hot-wheels-unleashed', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('hot-wheels-unleashed', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('hot-wheels-unleashed', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('hot-wheels-unleashed', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('injustice-2', 'Injustice 2: Legendary Edition', 'Fighting / DC Universe', 9.2, 2017, 'DC Fighting', 52, 55, 17000, 5000, 2000, '../shared/assets/covers/injustice-2.jpg', 'Power up and build the ultimate version of your favorite DC superheroes and villains.');
INSERT INTO game_platforms (game_id, platform) VALUES ('injustice-2', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('injustice-2', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('injustice-2', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('tlou-1', 'The Last of Us Remastered', 'Action / Narrative Survival', 9.9, 2014, 'Over 200 GOTY Awards', 48, 0, 16000, 4500, 2000, '../shared/assets/covers/tlou-1.jpg', 'Joel and Ellie journey across a post-pandemic United States. Unforgettable story.');
INSERT INTO game_platforms (game_id, platform) VALUES ('tlou-1', 'ps4');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('minecraft', 'Minecraft (PlayStation 4 Edition)', 'Sandbox / Survival', 9.5, 2019, 'Top Sandbox', 6, 8, 16000, 4000, 1500, '../shared/assets/covers/minecraft.jpg', 'Endless creativity and survival. Build anything you can imagine with infinite blocks.');
INSERT INTO game_platforms (game_id, platform) VALUES ('minecraft', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('minecraft', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('minecraft', 'pc');
INSERT INTO game_platforms (game_id, platform) VALUES ('minecraft', 'ps3');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('it-takes-two', 'It Takes Two', 'Co-op Platformer / Adventure', 9.8, 2021, 'Game of the Year', 45, 50, 22000, 5500, 2000, '../shared/assets/covers/it-takes-two.jpg', 'A genre-bending platform adventure created purely for two-player co-op gameplay.');
INSERT INTO game_platforms (game_id, platform) VALUES ('it-takes-two', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('it-takes-two', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('it-takes-two', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('it-takes-two', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('tlou-2', 'The Last of Us Part II', 'Action / Survival Horror', 9.7, 2020, 'PlayStation Masterpiece', 80, 0, 22000, 6000, 2500, '../shared/assets/covers/tlou-2.jpg', 'An emotional, visceral journey of vengeance across post-apocalyptic Seattle.');
INSERT INTO game_platforms (game_id, platform) VALUES ('tlou-2', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('tlou-2', 'ps5');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('motogp-24', 'MotoGP 24', 'Motorcycle Racing / Sim', 8.8, 2024, 'Official MotoGP', 28, 30, 28000, 6500, 2500, '../shared/assets/covers/motogp-24.jpg', 'Official 2024 season with riders market transfers and dynamic weather physics.');
INSERT INTO game_platforms (game_id, platform) VALUES ('motogp-24', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('motogp-24', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('motogp-24', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('motogp-24', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('kena-bridge-of-spirits', 'Kena: Bridge of Spirits', 'Action Adventure / Indie', 9.1, 2021, 'Deluxe Edition', 25, 28, 18000, 5000, 2000, '../shared/assets/covers/kena-bridge-of-spirits.jpg', 'A story-driven action adventure combining fast-paced combat with magical Rot companions.');
INSERT INTO game_platforms (game_id, platform) VALUES ('kena-bridge-of-spirits', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('kena-bridge-of-spirits', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('kena-bridge-of-spirits', 'pc');
INSERT INTO game_platforms (game_id, platform) VALUES ('kena-bridge-of-spirits', 'xbox');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('mafia-3', 'Mafia III', 'Crime / Open World', 8.4, 2016, 'Crime Drama', 50, 52, 15000, 4000, 2000, '../shared/assets/covers/mafia-3.jpg', 'Lincoln Clay builds a criminal empire in 1968 New Bordeaux to exact revenge.');
INSERT INTO game_platforms (game_id, platform) VALUES ('mafia-3', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('mafia-3', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('mafia-3', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('naruto-storm-connections', 'Naruto x Boruto Ultimate Ninja Storm Connections', 'Anime / Fighting', 8.9, 2023, 'Anime Fighting', 35, 38, 26000, 6000, 2500, '../shared/assets/covers/naruto-storm-connections.jpg', 'The largest ninja roster in history celebrating the anime 20th anniversary.');
INSERT INTO game_platforms (game_id, platform) VALUES ('naruto-storm-connections', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('naruto-storm-connections', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('naruto-storm-connections', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('naruto-storm-connections', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('nfs-heat', 'Need for Speed Heat', 'Street Racing', 8.9, 2019, 'Street Racing', 35, 40, 18000, 5000, 2000, '../shared/assets/covers/nfs-heat.jpg', 'Hustle by day in Speedhunters Showdown and risk it all by night in illicit street races.');
INSERT INTO game_platforms (game_id, platform) VALUES ('nfs-heat', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('nfs-heat', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('nfs-heat', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('re7-biohazard', 'Resident Evil 7: Biohazard', 'Survival Horror / First Person', 9.4, 2017, 'VR Compatible', 28, 30, 16000, 4500, 2000, '../shared/assets/covers/re7-biohazard.jpg', 'Ethan Winters searches for his wife in a derelict Louisiana plantation. Pure terror.');
INSERT INTO game_platforms (game_id, platform) VALUES ('re7-biohazard', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('re7-biohazard', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('re7-biohazard', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('re7-biohazard', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('sleeping-dogs', 'Sleeping Dogs: Definitive Edition', 'Martial Arts / Open World', 9.1, 2014, 'Martial Arts Classic', 20, 22, 14000, 4000, 1500, '../shared/assets/covers/sleeping-dogs.jpg', 'Undercover cop Wei Shen infiltrates the Sun On Yee Triad in neon-lit Hong Kong.');
INSERT INTO game_platforms (game_id, platform) VALUES ('sleeping-dogs', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('sleeping-dogs', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('sleeping-dogs', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('nfs-payback', 'Need for Speed Payback', 'Action Racing', 8.4, 2017, 'Action Driving', 30, 32, 15000, 4000, 2000, '../shared/assets/covers/nfs-payback.jpg', 'Take down the cartel ruling Fortune Valley casino underworld in blockbuster heist missions.');
INSERT INTO game_platforms (game_id, platform) VALUES ('nfs-payback', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('nfs-payback', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('nfs-payback', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('sekiro', 'Sekiro: Shadows Die Twice', 'Action / Souls-like', 9.8, 2019, 'Game of the Year', 25, 25, 24000, 6000, 2500, '../shared/assets/covers/sekiro.jpg', 'Carve your own clever path to vengeance as the One-Armed Wolf in Sengoku Japan.');
INSERT INTO game_platforms (game_id, platform) VALUES ('sekiro', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('sekiro', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('sekiro', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('spiderman-ps4', '', 'Action / Superhero', 9.7, 2018, 'PS4 Must-Play', 50, 65, 18000, 5000, 2000, '../shared/assets/covers/spiderman-ps4.jpg', 'A seasoned Peter Parker fights iconic villains across Manhattan with acrobatics and fluid webs.');
INSERT INTO game_platforms (game_id, platform) VALUES ('spiderman-ps4', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('spiderman-ps4', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('spiderman-ps4', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('re2-remake', 'Resident Evil 2 Remake', 'Survival Horror', 9.6, 2019, 'GOTY Nominee', 26, 28, 18000, 5000, 2000, '../shared/assets/covers/re2-remake.jpg', 'Raccoon City Police Station survival reimagined with modern over-the-shoulder perspective.');
INSERT INTO game_platforms (game_id, platform) VALUES ('re2-remake', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('re2-remake', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('re2-remake', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('re2-remake', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('shadow-tomb-raider', 'Shadow of the Tomb Raider: Definitive Edition', 'Action Adventure', 8.9, 2018, 'Definitive Edition', 40, 45, 16000, 4500, 2000, '../shared/assets/covers/shadow-tomb-raider.jpg', 'Lara Croft races to save the world from a Maya apocalypse in the deadliest jungles.');
INSERT INTO game_platforms (game_id, platform) VALUES ('shadow-tomb-raider', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('shadow-tomb-raider', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('shadow-tomb-raider', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('spiderman-miles-morales', '', 'Action / Superhero', 9.2, 2020, 'Must Play', 40, 45, 22000, 5000, 2000, '../shared/assets/covers/spiderman-miles-morales.jpg', 'Bio-electric venom blast attacks and covert camouflage power in snow-covered Harlem.');
INSERT INTO game_platforms (game_id, platform) VALUES ('spiderman-miles-morales', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('spiderman-miles-morales', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('spiderman-miles-morales', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('tennis-world-tour', 'Tennis World Tour', 'Sports / Tennis', 7.8, 2018, 'Tennis Pro', 10, 12, 12000, 3500, 1500, '../shared/assets/covers/tennis-world-tour.jpg', 'Play as Roger Federer and 30 other tennis stars across all major court surfaces.');
INSERT INTO game_platforms (game_id, platform) VALUES ('tennis-world-tour', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('tennis-world-tour', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('tennis-world-tour', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('ac-valhalla', '', 'Action RPG / Open World', 9.1, 2020, 'Viking Saga', 85, 95, 22000, 5500, 2000, '../shared/assets/covers/ac-valhalla.jpg', 'Lead legendary Viking raids against Saxon fortresses and conquer 9th-century England.');
INSERT INTO game_platforms (game_id, platform) VALUES ('ac-valhalla', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('ac-valhalla', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('ac-valhalla', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('ac-valhalla', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('god-of-war-2018', 'God of War (2018)', 'Action Adventure / Norse', 9.9, 2018, 'Game of the Year', 45, 50, 18000, 5000, 2000, '../shared/assets/covers/god-of-war-2018.jpg', 'Kratos and Atreus journey through the brutal realm of Norse gods and monsters.');
INSERT INTO game_platforms (game_id, platform) VALUES ('god-of-war-2018', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('god-of-war-2018', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('ufc-4', 'EA SPORTS UFC 4', 'Combat Sports / MMA', 8.9, 2020, 'Fight Champion', 40, 0, 18000, 5000, 2000, '../shared/assets/covers/ufc-4.jpg', 'Fluid clinch-to-strike combinations and responsive takedown grappling in the Octagon.');
INSERT INTO game_platforms (game_id, platform) VALUES ('ufc-4', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('ufc-4', 'xbox');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('dmc-5', 'Devil May Cry 5', 'Hack & Slash / Action', 9.4, 2019, 'Stylish Action', 35, 40, 18000, 5000, 2000, '../shared/assets/covers/dmc-5.jpg', 'High-octane stylized combat featuring Dante, Nero, and V battling demonic hordes.');
INSERT INTO game_platforms (game_id, platform) VALUES ('dmc-5', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('dmc-5', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('dmc-5', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('dmc-5', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('hogwarts-legacy', 'Hogwarts Legacy', 'Open World RPG / Magic', 9.3, 2023, 'Wizarding World', 80, 85, 28000, 7000, 2500, '../shared/assets/covers/hogwarts-legacy.jpg', 'Live the unwritten in 1800s Hogwarts. Master spells, brew potions, and tame beasts.');
INSERT INTO game_platforms (game_id, platform) VALUES ('hogwarts-legacy', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('hogwarts-legacy', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('hogwarts-legacy', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('hogwarts-legacy', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('wwe-2k23', 'WWE 2K23', 'Sports / Wrestling', 8.9, 2023, 'Even Stronger', 65, 75, 22000, 5500, 2000, '../shared/assets/covers/wwe-2k23.jpg', 'WarGames match debut, John Cena 20-year Showcase, and deep Superstar roster.');
INSERT INTO game_platforms (game_id, platform) VALUES ('wwe-2k23', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('wwe-2k23', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('wwe-2k23', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('wwe-2k23', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('god-of-war-ragnarok', 'God of War RagnarÃ¶k', 'Action / Mythological', 9.8, 2022, 'Masterpiece', 107, 190, 32000, 7000, 3000, '../shared/assets/covers/gow-ragnarok.jpg', 'Fimbulwinter is underway. Kratos and Atreus must journey to each of the Nine Realms.');
INSERT INTO game_platforms (game_id, platform) VALUES ('god-of-war-ragnarok', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('god-of-war-ragnarok', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('god-of-war-ragnarok', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('infamous-second-son', 'inFAMOUS Second Son', 'Superhero / Action', 8.8, 2014, 'Superpowers', 24, 0, 14000, 4000, 1500, '../shared/assets/covers/infamous-second-son.jpg', 'Delsin Rowe wields smoke, neon, and video superpowers in locked-down Seattle.');
INSERT INTO game_platforms (game_id, platform) VALUES ('infamous-second-son', 'ps4');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('jurassic-world-evolution', 'Jurassic World Evolution', 'Dinosaur Simulation / Strategy', 8.7, 2018, 'Park Builder', 15, 16, 15000, 4500, 2000, '../shared/assets/covers/jurassic-world-evolution.jpg', 'Bioengineer new dinosaurs and build attractions on legendary islands of the Muertes Archipelago.');
INSERT INTO game_platforms (game_id, platform) VALUES ('jurassic-world-evolution', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('jurassic-world-evolution', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('jurassic-world-evolution', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('motogp-19', 'MotoGP 19', 'Motorcycle Racing / Sim', 8.5, 2019, 'Racing Sim', 20, 22, 14000, 3500, 1500, '../shared/assets/covers/motogp-19.jpg', 'Neural AI racing and historical challenges featuring legendary riders.');
INSERT INTO game_platforms (game_id, platform) VALUES ('motogp-19', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('motogp-19', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('motogp-19', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('rdr2', 'Red Dead Redemption 2', 'Western / Open World', 9.9, 2018, 'Rockstar Masterpiece', 105, 120, 22000, 6000, 2500, '../shared/assets/covers/rdr2.jpg', 'Arthur Morgan and the Van der Linde gang on the run across the rugged heart of America.');
INSERT INTO game_platforms (game_id, platform) VALUES ('rdr2', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('rdr2', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('rdr2', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('lego-marvel-collection', 'LEGO Marvel Collection', 'Action / Adventure / LEGO', 9, 2019, '3 Games in 1', 45, 50, 18000, 5000, 2000, '../shared/assets/covers/lego-marvel-collection.jpg', 'Includes LEGO Marvel Super Heroes 1 & 2 and LEGO Marvel Avengers with all season passes.');
INSERT INTO game_platforms (game_id, platform) VALUES ('lego-marvel-collection', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('lego-marvel-collection', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('lego-marvel-collection', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('naruto-storm-4', 'Naruto Shippuden: Ultimate Ninja Storm 4', 'Anime / Fighting', 9.5, 2016, 'Anime Classic', 40, 42, 16000, 4500, 2000, '../shared/assets/covers/naruto-storm-4.jpg', 'The epic climax of the Fourth Great Ninja War with huge cinematic boss battles.');
INSERT INTO game_platforms (game_id, platform) VALUES ('naruto-storm-4', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('naruto-storm-4', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('naruto-storm-4', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('re4-remake', 'Resident Evil 4 Remake', 'Action Horror', 9.7, 2023, 'Survival Hit', 68, 72, 26000, 6500, 2500, '../shared/assets/covers/re4-remake.jpg', 'Leon S. Kennedy rescues the president daughter from a horrifying European cult.');
INSERT INTO game_platforms (game_id, platform) VALUES ('re4-remake', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('re4-remake', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('re4-remake', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('re4-remake', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('lego-incredibles', 'LEGO The Incredibles', 'Family / Co-op Adventure', 8.6, 2018, 'Family Co-op', 18, 20, 14000, 4000, 1500, '../shared/assets/covers/lego-incredibles.jpg', 'Experience the thrilling adventures of the Parr superhero family across both Incredibles films.');
INSERT INTO game_platforms (game_id, platform) VALUES ('lego-incredibles', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('lego-incredibles', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('lego-incredibles', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('overcooked-2', 'Overcooked! 2', 'Co-op Party / Cooking Arcade', 9.2, 2018, 'Chaotic Party Game', 8, 10, 15000, 4000, 1500, '../shared/assets/covers/overcooked-2.jpg', 'Chop, cook, and serve dishes in hilarious high-pressure cooperative kitchens.');
INSERT INTO game_platforms (game_id, platform) VALUES ('overcooked-2', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('overcooked-2', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('overcooked-2', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('overcooked-2', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('team-sonic-racing', 'Team Sonic Racing', 'Kart Racing / Party', 8.5, 2019, 'Sonic Racing', 18, 20, 15000, 4000, 1500, '../shared/assets/covers/team-sonic-racing.jpg', 'Team-based arcade racing where sharing power-ups and speed boosts unlocks victory.');
INSERT INTO game_platforms (game_id, platform) VALUES ('team-sonic-racing', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('team-sonic-racing', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('team-sonic-racing', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('spongebob-cosmic-shake', 'SpongeBob SquarePants: The Cosmic Shake', '3D Platformer / Kids & Family', 8.7, 2023, 'Bikini Bottom Fun', 16, 18, 18000, 4500, 2000, '../shared/assets/covers/spongebob-cosmic-shake.jpg', 'Wish-granting Mermaid Tears open portals to 7 distinct Wishworlds in Bikini Bottom.');
INSERT INTO game_platforms (game_id, platform) VALUES ('spongebob-cosmic-shake', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('spongebob-cosmic-shake', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('spongebob-cosmic-shake', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('spongebob-cosmic-shake', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('metal-slug-tactics', 'Metal Slug Tactics', 'Tactical Strategy / Roguelite', 8.6, 2024, 'Retro Tactics', 10, 12, 20000, 5000, 2000, '../shared/assets/covers/metal-slug-tactics.jpg', 'Classic explosive run-and-gun combat reimagined as a dynamic tactical grid RPG.');
INSERT INTO game_platforms (game_id, platform) VALUES ('metal-slug-tactics', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('metal-slug-tactics', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('metal-slug-tactics', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('metal-slug-tactics', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('watch-dogs-legion', 'Watch Dogs: Legion', 'Hacking / Open World', 8.5, 2020, 'Play as Anyone', 45, 50, 18000, 5000, 2000, '../shared/assets/covers/watch-dogs-legion.jpg', 'Build a resistance of anyone you see in near-future London facing collapse.');
INSERT INTO game_platforms (game_id, platform) VALUES ('watch-dogs-legion', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('watch-dogs-legion', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('watch-dogs-legion', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('watch-dogs-legion', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('stray', 'Stray', 'Cyberpunk Adventure / Cat', 9.3, 2022, 'Award Winning', 14, 15, 18000, 5000, 2000, '../shared/assets/covers/stray.jpg', 'A stray cat untangles an ancient mystery to escape a cybercity populated by droids.');
INSERT INTO game_platforms (game_id, platform) VALUES ('stray', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('stray', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('stray', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('stray', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('batman-arkham-knight', 'Batman: Arkham Knight', 'Action / Superhero', 9.6, 2015, 'PlayStation Hit', 50, 55, 15000, 4500, 2000, '../shared/assets/covers/batman-arkham-knight.jpg', 'Drive the Batmobile through Gotham City to confront Scarecrow and the Arkham Knight.');
INSERT INTO game_platforms (game_id, platform) VALUES ('batman-arkham-knight', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('batman-arkham-knight', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('batman-arkham-knight', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('like-a-dragon-infinite-wealth', 'Like a Dragon: Infinite Wealth', 'Turn-Based RPG / Yakuza', 9.4, 2024, 'Epic RPG', 60, 70, 28000, 7000, 2500, '../shared/assets/covers/like-a-dragon-infinite-wealth.jpg', 'Two larger-than-life heroes, Ichiban Kasuga and Kazuma Kiryu, team up in Hawaii.');
INSERT INTO game_platforms (game_id, platform) VALUES ('like-a-dragon-infinite-wealth', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('like-a-dragon-infinite-wealth', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('like-a-dragon-infinite-wealth', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('like-a-dragon-infinite-wealth', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('watch-dogs-2', 'Watch Dogs 2', 'Hacking / Open World', 9, 2016, 'San Francisco Hacker', 38, 42, 15000, 4000, 2000, '../shared/assets/covers/watch-dogs-2.jpg', 'Play as brilliant young hacker Marcus Holloway in the San Francisco Bay Area.');
INSERT INTO game_platforms (game_id, platform) VALUES ('watch-dogs-2', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('watch-dogs-2', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('watch-dogs-2', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('gow-3-remastered', 'God of War III Remastered', 'Hack & Slash / Greek Myth', 9.4, 2015, 'Only on PlayStation', 40, 0, 15000, 4500, 2000, '../shared/assets/covers/gow-3-remastered.jpg', 'Kratos scales Mount Olympus to take down Zeus in brutal 1080p 60fps glory.');
INSERT INTO game_platforms (game_id, platform) VALUES ('gow-3-remastered', 'ps4');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('tekken-7', 'Tekken 7', 'Fighting / Martial Arts', 9.3, 2017, 'King of Iron Fist', 50, 55, 16000, 4500, 2000, '../shared/assets/covers/tekken-7.jpg', 'Discover the epic conclusion of the 20-year Mishima clan feud and Rage Art finishers.');
INSERT INTO game_platforms (game_id, platform) VALUES ('tekken-7', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('tekken-7', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('tekken-7', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('elden-ring', 'Elden Ring', 'Dark Fantasy / Open World RPG', 9.9, 2022, 'Game of the Year', 50, 60, 28000, 7000, 2500, '../shared/assets/covers/elden-ring.jpg', 'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring.');
INSERT INTO game_platforms (game_id, platform) VALUES ('elden-ring', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('elden-ring', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('elden-ring', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('elden-ring', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('upin-ipin-universe', 'Upin & Ipin Universe', 'Kids & Family / Adventure', 8.4, 2023, 'Kids Favorite', 12, 0, 14000, 4000, 1500, '../shared/assets/covers/upin-ipin-universe.jpg', 'Join the twin brothers in fun Kampung adventures, mini-games, and village exploration.');
INSERT INTO game_platforms (game_id, platform) VALUES ('upin-ipin-universe', 'ps4');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('witcher-3', 'The Witcher 3: Wild Hunt', 'Dark Fantasy / Action RPG', 9.9, 2015, 'Over 300 GOTY Awards', 50, 55, 18000, 5000, 2000, '../shared/assets/covers/witcher-3.jpg', 'Play as Geralt of Rivia, monster slayer for hire, hunting the Child of Prophecy.');
INSERT INTO game_platforms (game_id, platform) VALUES ('witcher-3', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('witcher-3', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('witcher-3', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('witcher-3', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('dbz-kakarot', 'Dragon Ball Z: Kakarot', 'Anime / Action RPG', 9.1, 2020, 'Anime RPG', 38, 40, 18000, 5000, 2000, '../shared/assets/covers/dbz-kakarot.jpg', 'Relive the story of Goku and other Z Fighters. Fish, eat, train, and battle Saiyans.');
INSERT INTO game_platforms (game_id, platform) VALUES ('dbz-kakarot', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('dbz-kakarot', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('dbz-kakarot', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('dbz-kakarot', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('re8-village', 'Resident Evil Village', 'Survival Horror / Action', 9.4, 2021, 'Award Winner', 35, 40, 20000, 5500, 2000, '../shared/assets/covers/re8-village.jpg', 'Ethan Winters battles terrifying new adversaries in a snow-capped European village.');
INSERT INTO game_platforms (game_id, platform) VALUES ('re8-village', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('re8-village', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('re8-village', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('re8-village', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('re3-remake', 'Resident Evil 3 Remake', 'Survival Horror / Action', 8.8, 2020, 'Escape Nemesis', 25, 28, 16000, 4500, 2000, '../shared/assets/covers/re3-remake.jpg', 'Jill Valentine attempts a desperate escape from Raccoon City while pursued by Nemesis.');
INSERT INTO game_platforms (game_id, platform) VALUES ('re3-remake', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('re3-remake', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('re3-remake', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('re3-remake', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('gta-trilogy', 'Grand Theft Auto: The Trilogy â€“ The Definitive Edition', 'Open World / Crime Action', 8.6, 2021, '3 Classic Games', 40, 45, 20000, 5500, 2000, '../shared/assets/covers/gta-trilogy.jpg', 'Play the genre-defining classics: GTA III, GTA Vice City, and GTA San Andreas remastered.');
INSERT INTO game_platforms (game_id, platform) VALUES ('gta-trilogy', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('gta-trilogy', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('gta-trilogy', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('gta-trilogy', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('uncharted-4', '', 'Cinematic Action Adventure', 9.8, 2016, 'Only on PlayStation', 50, 60, 16000, 4500, 2000, '../shared/assets/covers/uncharted-4.jpg', 'Nathan Drake is pulled back into the dangerous world of thieves in search of Libertalia.');
INSERT INTO game_platforms (game_id, platform) VALUES ('uncharted-4', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('uncharted-4', 'ps5');
INSERT INTO game_platforms (game_id, platform) VALUES ('uncharted-4', 'pc');
INSERT INTO games (id, title, genre, rating, release_year, badge, ps4_size_gb, pc_size_gb, cd_price, online_price, modded_price, cover_path, description) VALUES ('re6', 'Resident Evil 6', 'Action Horror / Co-op', 8.4, 2016, '4 Campaigns', 20, 22, 14000, 4000, 1500, '../shared/assets/covers/re6.jpg', 'Four intertwined campaigns featuring Leon, Chris, Jake, and Ada Wong battling global bioterrorism.');
INSERT INTO game_platforms (game_id, platform) VALUES ('re6', 'ps4');
INSERT INTO game_platforms (game_id, platform) VALUES ('re6', 'ps3');
INSERT INTO game_platforms (game_id, platform) VALUES ('re6', 'xbox');
INSERT INTO game_platforms (game_id, platform) VALUES ('re6', 'pc');

COMMIT;
